routes/web.php
<?php

use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\TranslationsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('language')->group(function (){
    Route::get('/', [TranslationsController::class, 'index'])->name('home');
    Route::resource('translators', TranslationsController::class);


    Auth::routes();

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

app/Models/Translator.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Translator extends Model implements TranslatableContract
{
    use HasFactory;
    use Translatable;

    /**
     * @var string[]
     */
    public $translatedAttributes = ['translation'];

    /**
     * @var string[]
     */
    protected $fillable = ['user_id'];


    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/TranslatorTranslation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TranslatorTranslation extends Model
{
    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var string[]
     */
    public $fillable = ['translation'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * @return HasMany
     */
    public function translators(): HasMany
    {
        return $this->hasMany(Translator::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LanguageSwitcherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class LanguageSwitcherController extends Controller
{
    /**
     * @param Request $request
     * @param string $locale
     * @return RedirectResponse
     */
    public function switcher(Request $request, string $locale):RedirectResponse
    {
        $request->session()->put('locale', $locale);
        return back();
    }
}

app/Http/Controllers/TranslationsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TranslationRequest;
use App\Models\Translator;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TranslationsController extends Controller
{


    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $translators = Translator::all();
        return view('translators.index', compact('translators'));

    }


    /**
     * @param TranslationRequest $request
     * @return RedirectResponse
     */
    public function store(TranslationRequest $request):RedirectResponse
    {
        $translation = new Translator();

        $user = Auth::user();
        $data = [ 'user_id' => $user->id,
            'ru' =>
                [
                    'translation' => $request->input('ru_translator'),
                ]
        ];

        $translation->create($data);

        return back();
    }


    /**
     * @param Translator $translator
     * @return Application|Factory|View
     */
    public function show(Translator $translator)
    {
        return view('translators.show', compact('translator'));
    }



    /**
     * @param Request $request
     * @param Translator $translator
     * @return RedirectResponse
     */
    public function update(Request $request, Translator $translator):RedirectResponse
    {
        if(!empty($request->input('en_translator'))) {
            $data = [
                'en' =>
                    [
                        'translation' => $request->input('en_translator'),
                    ]
            ];
            $translator->update($data);
        }
        if(!empty($request->input('uz_translator'))) {
            $data = [
                'uz' =>
                    [
                        'translation' => $request->input('uz_translator'),
                    ]
            ];
            $translator->update($data);
        }
        if(!empty($request->input('tat_translator'))) {
            $data = [
                'tat' =>
                    [
                        'translation' => $request->input('tat_translator'),
                    ]
            ];
            $translator->update($data);
        }
        if(!empty($request->input('ky_translator'))) {
            $data = [
                'ky' =>
                    [
                        'translation' => $request->input('ky_translator'),
                    ]
            ];
            $translator->update($data);
        }

        return back();
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('messages.dashboard')</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @lang('messages.logged_in')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">@lang('messages.login')</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">@lang('messages.register')</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        @lang('messages.logout')
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest

                        <select class="custom-select" onchange="location = this.value;">
                            <option @if (session('locale') == 'en') selected @endif value="{{route('language.switcher', 'en')}}">
                                EN
                            </option>
                            <option @if (session('locale') == 'ru') selected @endif value="{{route('language.switcher', 'ru')}}">
                                RU
                            </option>
                        </select>
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/translators/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container" >
        <h3>
            @lang('messages.translations')
        </h3>
        <div>
            @foreach($translators as $translator)
                <h5><a href="{{route('translators.show', ['translator' => $translator])}}">{{$translator->translate('ru')->translation}}</a></h5>
            @endforeach
        </div>
        @if(Auth::check())
            <div>
                <h5>
                    @lang('messages.create_new_translation')
                </h5>

                <form method="post" action="{{route('translators.store')}}">
                    @csrf

                    <div class="form-group">
                        <label for="ru_translator">@lang('messages.translation')</label>
                        <input name="ru_translator" type="text" class="form-control border-success  @error('translator') is-invalid border-danger @enderror"
                               id="ru_translator">
                    </div>
                    @error('translator')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror

                    <button type="submit" class="btn btn-primary">@lang('messages.save_translation')</button>
                </form>
            </div>
        @endif
    </div>
@endsection

resources/views/translators/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <dv>
            <h3>@lang('messages.translate') "{{$translator->translate('ru')->translation}}"</h3>
        </dv>
        @if(Auth::check())
            <form method="post" action="{{route('translators.update', ['translator' => $translator])}}">
                @method('put')
                @csrf
                <input type="hidden" id="translation_id" value="{{$translator->id}}">
                @if(!empty($translator->translate('ru')->translation))
                    <h4>{{$translator->translate('ru')->translation}}</h4>
                @else
                    <div class="form-group">
                        <label for="ru_translation">@lang('messages.russian')</label>
                        <input name="ru_translation"  type="text" class="form-control"
                               id="ru_translation">
                    </div>
                @endif
                @if(!empty($translator->translate('en')->translation))
                    <h4>{{$translator->translate('en')->translation}}</h4>
                @else
                    <div class="form-group">
                        <label for="en_translation">@lang('messages.english')</label>
                        <input name="en_translation"  type="text" class="form-control"
                               id="en_translation">
                    </div>
                @endif
                @if(!empty($translator->translate('uz')->translation))
                    <h4>{{$translator->translate('uz')->translation}}</h4>
                @else
                    <div class="form-group">
                        <label for="uz_translation">@lang('messages.uzbek')</label>
                        <input name="uz_translation" type="text" class="form-control"
                               id="uz_translation">
                    </div>
                @endif
                @if(!empty($translator->translate('tat')->translation))
                    <h4>{{$translator->translate('tat')->translation}}</h4>
                @else
                    <div class="form-group">
                        <label for="tat_translation">@lang('messages.tatar')</label>
                        <input name="tat_translation" type="text" class="form-control"
                               id="tat_translation" >
                    </div>
                @endif
                @if(!empty($translator->translate('ky')->translation))
                    <h4>{{$translator->translate('ky')->translation}}</h4>
                @else
                    <div class="form-group">
                        <label for="ky_translation">@lang('messages.kyrgyz')</label>
                        <input name="ky_translation" type="text" class="form-control"
                               id="ky_translation" >
                    </div>
                @endif
                <button type="submit" class="btn btn-primary">@lang('messages.save_translation')</button>
            </form>
        @else
            @if(!empty($translator->translate('ru')->translation))
                <div>
                    <b>@lang('messages.translate_ru')</b><br>
                    <h5>
                        {{$translator->translate('ru')->translation}}
                    </h5>
                </div>
            @endif

            @if(!empty($translator->translate('en')->translation))
                <div>
                    <b>@lang('messages.translate_en')</b><br>
                    <h5>
                        {{$translator->translate('en')->translation}}
                    </h5>
                </div>
            @endif

            @if(!empty($translator->translate('uz')->translation))
                <div>
                    <b>@lang('messages.translate_uz')</b><br>
                    <h5>
                        {{$translator->translate('uz')->translation}}
                    </h5>
                </div>
            @endif
            @if(!empty($translator->translate('tat')->translation))
                <div>
                    <b>@lang('messages.translate_tat')</b><br>
                    <h5>
                        {{$translator->translate('tat')->translation}}
                    </h5>
                </div>
            @endif
            @if(!empty($translator->translate('ky')->translation))
                <div>
                    <b>@lang('messages.translate_ky')</b><br>
                    <h5>
                        {{$translator->translate('ky')->translation}}
                    </h5>
                </div>
            @endif
        @endif
    </div>

@endsection